---
title: "compare setbp1 targets to spliceosome components"
output: html_document
date: "2024-02-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SETBP1 target overlap exploration

The purpose of this script is to compare setbp1 targets to spliceosome components. It is not dependent on any other scripts to run. It can be run in any docker.

## Load Packages

```{r load packages}
suppressPackageStartupMessages({
  # Load Lasseigne Lab standard packages
  library(here)
  library(styler)
  library(lintr)
  library(tidyverse)
  library(patchwork)
  library(ComplexHeatmap)
  library(viridis)
})

```



```{r compare to known setbp1 targets}

setbp1_targets <- read_csv("/data/project/lasseigne_lab/JordanWhitlock/230227_Setbp1Manuscript/230227_JW_Setbp1Manuscript_EVERYTHING/results/seurat/setbp1_targets.csv", col_types = cols(...1 = col_skip()))

setbp1_targets <- as.vector(setbp1_targets)

setbp1_targets <- setbp1_targets[[1]]

spliceosome_components <- c("SNRPGP15,RNU4ATAC,RNU6ATAC,RNVU1-8,RNVU1-4,RNVU1-14,RNVU1-15,,RNVU1-17,RNU6-9,RNVU1-3,RNVU1-1,RNU6-7,RNVU1-6,RNVU1-19,SF3A1,CD2BP2,PPIH,TAF12-DT,ARFGEF1,SLU7,PRPF8,HEXIM1,USP39,ENSG00000259697,TXNL4A,SF3A3,SF3B2,LSM6,RN7SK,LSM11,OVAAL,ZMAT2,SNRNP200,SF3B3,SF3B1,LSM5,PRPF6,PRPF40B,LSM4,AAR2,PRPF31,RNU11,RNU6-1,RNU5F-1,RNU5E-1,RNU5D-1,RNU5A-1,RNU5B-1,RNU4-2,RNU4-1,RNVU1-7,LSM3,HTATSF1,WEE2-AS1,SNU13,GEMIN4,LARP7,LUC7L2,RBMX2,SF3B6,LSM7,LSM8,LUC7L3,TXNL4B,PRPF39,PRPF40A,LUC7L,MEPCE,LSM2,RNU1-4,RNVU1-2A,RNU2-1,SNRNP70,SNRPA,SNRPA1,SNRPB,SNRPB2,SNRPC,SNRPD1,SNRPD2,SNRPD3,SNRPE,SNRPF,SNRPG,SNRPN,DDX39B,SF3A2,SF3B5,PHF5A,LSM10,PRPF18,SART1,PRPF4,PRPF3,EFTUD2,SNRNP40,DDX23,TGS1,SART3")

spliceosome_components <- strsplit(spliceosome_components, ',')[[1]]

spliceosome_components <- convert_human_gene_list(spliceosome_components)

overlapping_components <- intersect(setbp1_targets, spliceosome_components)

```



