---
title: "Compare cell types to JW"
author: "Emma Jones"
date: "2023-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages

```{r load packages}
suppressPackageStartupMessages({
  # Load Lasseigne Lab standard packages
  library(here)
  library(styler)
  library(lintr)

  # Load Seurat and other single-cell packages
  library(tidyverse)
  library(Seurat)
  library(patchwork)
  library(harmony)
  library(presto)
  })

# set seed
set.seed(123)
```



```{r load ej data}

clustered_brain_samples <- readRDS("/data/user/efjones/230926_EJ_Setbp1_AlternativeSplicing/data/seurat/clustered_brain_samples.rds")

```



```{r load jw data}
load("/data/project/lasseigne_lab/JordanWhitlock/230227_Setbp1Manuscript/230227_JW_Setbp1Manuscript_EVERYTHING/data/setbp1_cerebralintcelltypes.Rdata")

```


```{r look at overlapping barcodes}
# make names match
EJ_cells <- paste0(filtered_brain_samples@meta.data[["cells"]], "-1")
# df has slightly different structure in seurat version workflows
JW_cells <- cerebral_int_celltypes@assays[["RNA"]]@counts@Dimnames[[2]]

overlapping_cells <- intersect(EJ_cells, JW_cells) # 51028 cells, so that is a

length(overlapping_cells) / length(EJ_cells) # .9915088 or 99% overlap with me

length(overlapping_cells) / length(JW_cells) # and 99.9% of JW's cells

EJ_only <- setdiff(EJ_cells, JW_cells) # 437

JW_only <- setdiff(JW_cells, EJ_cells) # only 10 cells!

```

```{r}
```

```{r}
```

```{r}
```
